add file app.js and modified index.html, main.css
new-hope/Second-example2 pull request #2
Opened 2017-01-10 14:22 UTC by Grishchenko

2017-01-10 15:25 UTC, yarigpopov requested changes
I added some comments. please make changes (or reply with questions)

2017-01-10 15:25 UTC, chilicoder commented on main.css
> +}
github likes empty newline in the end of the file. add one here

2017-01-10 15:25 UTC, chilicoder commented on index.html
> +	<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
duplicate (you already have one in the head)

2017-01-10 15:25 UTC, chilicoder commented on app.js
> +});
add newline here

2017-01-10 15:34 UTC, Grishchenko commented on main.css
> +}
Слав, а почему он так любит?

2017-01-10 15:35 UTC, Grishchenko commented on index.html
> +	<script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
Это косяк. Хотел другое сделать.

2017-01-10 20:30 UTC, chilicoder commented on main.css
> +}
https://www.quora.com/Why-is-it-a-common-practice-to-put-a-new-line-at-the-end-of-a-source-code-file

2017-01-10 20:31 UTC, chilicoder commented on main.css
> +}
на всякий случай, для целостности. иногда в каких то случаях чтото читающее может не прочитать последнюю строку и тогда будет баг, который в жизни не обнаружишь. 

в общем, более подробно по ссылке

2017-01-10 20:32 UTC, chilicoder commented on index.html
>  </html>
тоже newline

2017-01-11 09:20 UTC, Grishchenko reviewed
исправил

2017-01-11 10:18 UTC, yarigpopov approved these changes

2017-01-11 10:18 UTC, merged